package sdk_rpc

const (
	EthAccounts                            = "eth_accounts"
	EthBlockNumber                         = "eth_blockNumber"
	EthCall                                = "eth_call"
	EthChainId                             = "eth_chainId"
	EthCoinbase                            = "eth_coinbase"
	EthEstiMateGas                         = "eth_estimateGas"
	EthGasPrice                            = "eth_gasPrice"
	EthGetBalance                          = "eth_getBalance"
	EthGetBlockByHash                      = "eth_getBlockByHash"
	EthGetBlockByNumber                    = "eth_getBlockByNumber"
	EthGetBlockTransactionCountByHash      = "eth_getBlockTransactionCountByHash"
	EthGetBlockTransactionCountByNumber    = "eth_getBlockTransactionCountByNumber"
	EthGetCode                             = "eth_getCode"
	EthGetStorageAt                        = "eth_getStorageAt"
	EthGetTransactionByBlockHashAndIndex   = "eth_getTransactionByBlockHashAndIndex"
	EthGetTransactionByBlockNumberAndIndex = "eth_getTransactionByBlockNumberAndIndex"
	EthGetTransactionByHash                = "eth_getTransactionByHash"
	EthGetTransactionReceipt               = "eth_getTransactionReceipt"
	EthGetWork                             = "eth_getWork"
	EthProtocolVersion                     = "eth_protocolVersion"
	EthSyncing                             = "eth_syncing"
	EthNewFilter                           = "eth_newFilter"
	EthNewBlockFilter                      = "eth_newBlockFilter"
	EthGetFilterChanges                    = "eth_getFilterChanges"
	EthGetFilterLogs                       = "eth_getFilterLogs"
	EthUninstallFilter                     = "eth_uninstallFilter"
	EthGetLogs                             = "eth_getLogs"
	NetListening                           = "net_listening"
	NetPeerCount                           = "net_peerCount"
	NetVersion                             = "net_version"
	Web3ClientVersion                      = "web3_clientVersion"
	Web3Sha3                               = "web3_sha3"
	BuildTransaction                       = "buildTransaction"
)
