package methods

const (
	// -------------------------------------------------------------
	//                FULL NODE HTTP API METHODS
	// -------------------------------------------------------------

	Validateaddress                    = "/wallet/validateaddress"
	Broadcasttransaction               = "/wallet/broadcasttransaction"
	BroadcastHex                       = "/wallet/broadcasthex"
	CreateTransaction                  = "/wallet/createtransaction"
	CreateAccount                      = "/wallet/createaccount"
	GetAccount                         = "/wallet/getaccount"
	UpdateAccount                      = "/wallet/updateaccount"
	AccountPermissionUpdate            = "/wallet/accountpermissionupdate"
	GetAccountBalance                  = "/wallet/getaccountbalance"
	GetAccountResource                 = "/wallet/getaccountresource"
	GetAccountNet                      = "/wallet/getaccountnet"
	UnfreezeBalance                    = "/wallet/unfreezebalance"
	GetDelegatedResource               = "/wallet/getdelegatedresource"
	GetDelegatedResourceAccountIndex   = "/wallet/getdelegatedresourceaccountindex"
	FreezeBalanceV2                    = "/wallet/freezebalancev2"
	UnfreezeBalanceV2                  = "/wallet/unfreezebalancev2"
	CancelAllUnfreezeV2                = "/wallet/cancelallunfreezev2"
	DelegateResource                   = "/wallet/delegateresource"
	UnDelegateResource                 = "/wallet/undelegateresource"
	WithdrawExpireUnfreeze             = "/wallet/withdrawexpireunfreeze"
	GetAvailableUnfreezeCount          = "/wallet/getavailableunfreezecount"
	GetCanWithdrawUnfreezeAmount       = "/wallet/getcanwithdrawunfreezeamount"
	GetCanDelegatedMaxSize             = "/wallet/getcandelegatedmaxsize"
	GetDelegatedResourceV2             = "/wallet/getdelegatedresourcev2"
	GetDelegatedResourceAccountIndexV2 = "/wallet/getdelegatedresourceaccountindexv2"
	GetBlock                           = "/wallet/getblock"
	GetBlockByNum                      = "/wallet/getblockbynum"
	GetBlockById                       = "/wallet/getblockbyid"
	GetBlockByLatestNum                = "/wallet/getblockbylatestnum"
	GetBlockByLimitNext                = "/wallet/getblockbylimitnext"
	GetNowBlock                        = "/wallet/getnowblock"
	GetTransactionById                 = "/wallet/gettransactionbyid"
	GetTransactionInfoById             = "/wallet/gettransactioninfobyid"
	GetTransactionInfoByBlockNum       = "/wallet/gettransactioninfobyblocknum"
	GetTransactionCountByBlockNum      = "/wallet/gettransactioncountbyblocknum"
	ListNodes                          = "/wallet/listnodes"
	GetNodeInfo                        = "/wallet/getnodeinfo"
	GetChainParameters                 = "/wallet/getchainparameters"
	GetBlockBalance                    = "/wallet/getblockbalance"
	GetEnergyPrices                    = "/wallet/getenergyprices"
	GetBandwidthPrices                 = "/wallet/getbandwidthprices"
	GetBurnTRX                         = "/wallet/getburntrx"
	GetApprovedList                    = "/wallet/getapprovedlist"
	GetAssetIssueByAccount             = "/wallet/getassetissuebyaccount"
	GetAssetIssueById                  = "/wallet/getassetissuebyid"
	GetAssetIssueByName                = "/wallet/getassetissuebyname"
	GetAssetIssueList                  = "/wallet/getassetissuelist"
	GetAssetIssueListByName            = "/wallet/getassetissuelistbyname"
	GetPaginatedAssetIssueList         = "/wallet/getpaginatedassetissuelist"
	TransferAsset                      = "/wallet/transferasset"
	CreateAssetIssue                   = "/wallet/createassetissue"
	ParticipateAssetIssue              = "/wallet/participateassetissue"
	UnfreezeAsset                      = "/wallet/unfreezeasset"
	UpdateAsset                        = "/wallet/updateasset"
	GetContract                        = "/wallet/getcontract"
	GetContractInfo                    = "/wallet/getcontractinfo"
	TriggerSmartContract               = "/wallet/triggersmartcontract"
	TriggerConstantContract            = "/wallet/triggerconstantcontract"
	DeployContract                     = "/wallet/deploycontract"
	UpdateSetting                      = "/wallet/updatesetting"
	UpdateEnergyLimit                  = "/wallet/updateenergylimit"
	ClearAbi                           = "/wallet/clearabi"
	EstimateEnergy                     = "/wallet/estimateenergy"
	ListWitnesses                      = "/wallet/listwitnesses"
	CreateWitness                      = "/wallet/createwitness"
	UpdateWitness                      = "/wallet/updatewitness"
	GetBrokerage                       = "/wallet/getbrokerage"
	UpdateBrokerage                    = "/wallet/updatebrokerage"
	VoteWitnessAccount                 = "/wallet/votewitnessaccount"
	GetReward                          = "/wallet/getreward"
	WithdrawBalance                    = "/wallet/withdrawbalance"
	GetNextMaintenanceTime             = "/wallet/getnextmaintenancetime"
	ListProposals                      = "/wallet/listproposals"
	GetProposalById                    = "/wallet/getproposalbyid"
	ProposalCreate                     = "/wallet/proposalcreate"
	ProposalApprove                    = "/wallet/proposalapprove"
	ProposalDelete                     = "/wallet/proposaldelete"
	GetTransactionListFromPending      = "/wallet/gettransactionlistfrompending"
	GetTransactionFromPending          = "/wallet/gettransactionfrompending"
	GetPendingSize                     = "/wallet/getpendingsize"

	// -------------------------------------------------------------
	//                FULL NODE SOLIDITY HTTP API METHODS
	// -------------------------------------------------------------

	SolidityGetTransactionById                 = "/walletsolidity/gettransactionbyid"
	SolidityGetTransactionInfoById             = "/walletsolidity/gettransactioninfobyid"
	SolidityGetTransactionInfoByBlockNum       = "/walletsolidity/gettransactioninfobyblocknum"
	SolidityGetTransactionCountByBlockNum      = "/walletsolidity/gettransactioncountbyblocknum"
	SolidityGetBlock                           = "/walletsolidity/getblock"
	SolidityGetNowBlock                        = "/walletsolidity/getnowblock"
	SolidityGetBlockByNum                      = "/walletsolidity/getblockbynum"
	SolidityGetBlockById                       = "/walletsolidity/getblockbyid"
	SolidityGetBlockByLatestNum                = "/walletsolidity/getblockbylatestnum"
	SolidityGetBlockByLimitNext                = "/walletsolidity/getblockbylimitnext"
	SolidityGetAccount                         = "/walletsolidity/getaccount"
	SolidityGetDelegatedResource               = "/walletsolidity/getdelegatedresource"
	SolidityGetDelegatedResourceAccountIndex   = "/walletsolidity/getdelegatedresourceaccountindex"
	SolidityGetCanDelegatedMaxSize             = "/walletsolidity/getcandelegatedmaxsize"
	SolidityGetCanWithdrawUnfreezeAmount       = "/walletsolidity/getcanwithdrawunfreezeamount"
	SolidityGetDelegatedResourceAccountIndexV2 = "/walletsolidity/getdelegatedresourceaccountindexv2"
	SolidityGetAvailableUnfreezeCount          = "/walletsolidity/getavailableunfreezecount"
	SolidityGetNodeInfo                        = "/walletsolidity/getnodeinfo"
	SolidityGetBurnTRX                         = "/walletsolidity/getburntrx"
	SolidityTriggerConstantContract            = "/walletsolidity/triggerconstantcontract"
	SolidityEstimateEnergy                     = "/walletsolidity/estimateenergy"
	SolidityGetAssetIssueById                  = "/walletsolidity/getassetissuebyid"
	SolidityGetAssetIssueByName                = "/walletsolidity/getassetissuebyname"
	SolidityGetAssetIssueList                  = "/walletsolidity/getassetissuelist"
	SolidityGetAssetIssueListByName            = "/walletsolidity/getassetissuelistbyname"
	SolidityGetPaginatedAssetIssueList         = "/walletsolidity/getpaginatedassetissuelist"
	SolidityListWitnesses                      = "/walletsolidity/listwitnesses"
	SolidityGetReward                          = "/walletsolidity/getreward"
	SolidityGetBrokerage                       = "/walletsolidity/getbrokerage"
)
